steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
  
    args: ['build', '--build-arg',
         'degrado=${_DEGRADO}',
         '-f', 'cloud-dockerfile.dockerfile', 
         '-t', 'europe-west12-docker.pkg.dev/architecture-degradi/ml-inference-repo/${_DEGRADO}-service:latest', '.']
    
    env:
      - DOCKER_BUILDKIT=1
      
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west12-docker.pkg.dev/architecture-degradi/ml-inference-repo/${_DEGRADO}-service:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_DEGRADO}-service'
      - '--image'
      - 'europe-west12-docker.pkg.dev/architecture-degradi/ml-inference-repo/${_DEGRADO}-service:latest'
      - '--region'
      - 'europe-west12'
      - '--allow-unauthenticated'
      - '--memory'
      - '32Gi'
      - '--cpu'
      - '8'
      - '--timeout'
      - '900'
      - '--max-instances'
      - '5'
      - '--concurrency'
      - '2'
      - '--set-env-vars'
      - 'MODEL_NAME=unet-efficient-b3-${_DEGRADO}.pth,MASK_THRESHOLD=0.8'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY